DEEPSORT:
  REID_CKPT: "/home/sai/yolov8_deepsort_jetson/model/deepsort.engine"
  MAX_DIST: 0.3
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100
  
